### ISSUE TITLE
Include varying height bars

### ISSUE THREAD

**Issue by hadley** [r-pkgs/boxes#1]
From https://github.com/hadley/precis/blob/master/R/histospark.R

**Comment by gaborcsardi** [comment]
You mean in `rule`? You can, already, but we can provide some shortcuts:
```
❯ cat(rule(center = "TITLE", line = "\u2583"))
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃ TITLE ▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
```

**Comment by gaborcsardi** [comment]
Btw. for these we need a fallback if UTF-8 characters are not available....

**Comment by hadley** [comment]
I meant a helper that would map from [0, 1] to a bar

**Comment by gaborcsardi** [comment]
Oh, OK, makes sense.

**Comment by gaborcsardi** [comment]
But I suppose you don't want to create the sparklines with this package?

**Comment by hadley** [comment]
That feels out-of-scope to me. I'd say boxes should have a function that takes a numeric vector with values between 0 and 1 and returns a single string.

**Comment by gaborcsardi** [comment]
Unfortunately these blocks are not available in the default font in RGui.... so I'll have some replacements...

**Comment by gaborcsardi** [comment]
This exists already, actually:
```r
spark::spark(runif(50))
▂▃▇▃▂▅▂▁▄▃▃▃▆▂▇▂██▆▂▄▆▃▅▂▃▂▆▁▆▆▁█▇█▄▁▁▂▂▆▇▇▅▆▂▄▃▂█
```

**Comment by gaborcsardi** [comment]
I will brush up `spark` a bit...

**Comment by gaborcsardi** [comment]
`spark` should be good now, once the `clisymbols` update is on CRAN, I'll submit it.
