### ISSUE TITLE
Some wrappers around format?

### ISSUE THREAD

**Issue by hadley** [r-pkgs/boxes#2]
For common cases of left, right, and center aligning. Not sure if it belongs in this package, but it's somewhat related to drawing boxes because it makes columns the same width. 

Could also include more sophisticated alignment on decimal place along with specified number of sig figs.

**Comment by hadley** [comment]
See https://github.com/tidyverse/tibble/issues/30 for more discussion.

**Comment by gaborcsardi** [comment]
I think this belongs to the (future) `ansistrings` package, and until that is done, to `crayon`. I have a `col_align` function somewhere that aligns while keeping the color, I'll put that in `crayon`.

**Comment by gaborcsardi** [comment]
As for the alignment on decimal place, that can be in a table formatting package, like `tab` or `tibble`, which already does a lot about formatting.

**Comment by gaborcsardi** [comment]
OK, `crayon` has a `col_align` function now.
